# -*- coding: utf-8 -*-
"""FinalExam2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWlcSVKidsjvlpX4UB2LUNRKQl38vE9L
"""

import numpy as np
import matplotlib.pyplot as plt

# Simulate product return data (e.g. 100 months)
np.random.seed(2025)
true_mu = 5
true_sigma = 1.5
data = np.random.normal(true_mu, true_sigma, size=100)

# Priors
prior_mu_mean = 4
prior_mu_precision = 0.4
prior_sigma_alpha = 2
prior_sigma_beta = 1

# Posterior updates
posterior_mu_precision = prior_mu_precision + len(data) / true_sigma**2
posterior_mu_mean = (prior_mu_precision * prior_mu_mean + np.sum(data)) / posterior_mu_precision

posterior_sigma_alpha = prior_sigma_alpha + len(data) / 2
posterior_sigma_beta = prior_sigma_beta + np.sum((data - np.mean(data))**2) / 2

# Sampling posterior
posterior_mu = np.random.normal(posterior_mu_mean, 1 / np.sqrt(posterior_mu_precision), size=10000)
posterior_sigma = np.random.gamma(posterior_sigma_alpha, 1 / posterior_sigma_beta, size=10000)

# Plot
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.hist(posterior_mu, bins=30, color='skyblue', edgecolor='black', density=True)
plt.title('Posterior of Avg Monthly Returns (μ)')
plt.subplot(1, 2, 2)
plt.hist(posterior_sigma, bins=30, color='lightgreen', edgecolor='black', density=True)
plt.title('Posterior of Std Dev of Returns (σ)')
plt.tight_layout()
plt.show()

print("Estimated mean of returns:", round(np.mean(posterior_mu), 2))
print("Estimated std dev of returns:", round(np.mean(posterior_sigma), 2))