# -*- coding: utf-8 -*-
"""FinalExam3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RuusHEa3qbUYDiwLMJzfJ6LLTMl7uj8q
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Prior
mu_prior = 30
sigma_prior = 5

# Observations
data = np.array([32, 29, 31, 28, 33])
n = len(data)
mean_data = np.mean(data)
sigma_data = 2  # std dev of observed data

# Posterior parameters using conjugate prior for Normal
sigma_post_sq = 1 / (n / sigma_data**2 + 1 / sigma_prior**2)
mu_post = sigma_post_sq * (mean_data * n / sigma_data**2 + mu_prior / sigma_prior**2)
sigma_post = np.sqrt(sigma_post_sq)

# Plotting
x = np.linspace(20, 40, 1000)
plt.plot(x, norm.pdf(x, mu_prior, sigma_prior), '--', label='Prior N(30, 5²)')
plt.plot(x, norm.pdf(x, mu_post, sigma_post), label=f'Posterior N({mu_post:.2f}, {sigma_post:.2f}²)')
plt.title('Bayesian Update: Delivery Time')
plt.xlabel('Delivery Time (minutes)')
plt.ylabel('Density')
plt.legend()
plt.grid()
plt.show()