# -*- coding: utf-8 -*-
"""FinalExam1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P70isZpiBR0U-7KMmwr8uSyWLgGilzHB
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

#In Mandaluyong City, 10 out of 15 surveyed food app users reported experiencing food insecurity. Assuming a Beta(2, 2) prior for the probability of food insecurity among app users, compute the posterior distribution.

# Prior: Beta(2, 2)
a_prior = 2
b_prior = 2

# Data: 10 food insecure out of 15
successes = 10
failures = 5

# Posterior: Beta(2+10, 2+5) = Beta(12, 7)
a_post = a_prior + successes
b_post = b_prior + failures

x = np.linspace(0, 1, 1000)
plt.plot(x, beta.pdf(x, a_post, b_post), label='Posterior Beta(12, 7)')
plt.plot(x, beta.pdf(x, a_prior, b_prior), linestyle='--', label='Prior Beta(2, 2)')
plt.title('Bayesian Update: Food Insecurity')
plt.xlabel('Probability of Insecurity')
plt.ylabel('Density')
plt.legend()
plt.grid()
plt.show()