# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YaXc0ORrEkwobB_HyCVVAFKqFUkNasLC
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

alpha_prior = 4  # Prior "has access" count (e.g., 4 out of 10)
beta_prior = 6   # Prior "no access" count (e.g., 6 out of 10)

alpha_likelihood = alpha_prior + 7
beta_likelihood = beta_prior + 3  # The remaining 3 do not use food apps

x = np.linspace(0, 1, 100)

prior = beta.pdf(x, alpha_prior, beta_prior)
posterior = beta.pdf(x, alpha_likelihood, beta_likelihood)

plt.figure(figsize=(10, 5))
plt.plot(x, prior, label="Prior (Before Survey)", linestyle="--")
plt.plot(x, posterior, label="Posterior (After Survey)", linewidth=2)
plt.xlabel("Probability of Food App Access")
plt.ylabel("Probability Density")
plt.legend()
plt.title("Bayesian Inference: Food App Access in Low-Income Areas")
plt.show()