# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwGy1gdawgr24qn1KAe6MZKQWb9951F9
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

mu_prior = 1.7
sigma_prior = 0.1

observed_height = 1.75

mu_values = np.linspace(1.65, 1.8, 100)

prior = norm.pdf(mu_values, mu_prior, sigma_prior)
likelihood = norm.pdf(observed_height, mu_values, 0.1)

posterior = likelihood * prior
posterior /= np.sum(posterior)

plt.figure(figsize=(10, 5))
plt.plot(mu_values, prior, label="Prior", linestyle="--")
plt.plot(mu_values, likelihood, label="Likelihood", linestyle=":")
plt.plot(mu_values, posterior, label="Posterior", linewidth=2)
plt.xlabel("Mu (Mean Height)")
plt.ylabel("Probability Density")
plt.legend()
plt.title("Bayesian Inference: Prior, Likelihood, and Posterior")
plt.show()